respuestas = {
            "causas": ["La ansiedad puede ser causada por las siguientes condiciones: \n\n"
                       "-Medicamentos \n"
                       "-Medicamentos a base de hierbas \n"
                       "-Abuso de sustancias \n"
                       "-Trauma \n"
                       "-Experiencias de la infancia \n"
                       "-Trastornos de pánico", "La ansiedad puede surgir debido a diversas circunstancias, que incluyen:\n\n Uso de medicamentos.\n Consumo de productos naturales a base de hierbas.\n Abuso de sustancias.\n Experiencias traumáticas.\n Eventos o vivencias de la infancia.\n La presencia de trastornos de pánico.",
                       "Las causas de la  ansiedad suelen ser el resultado de una combinación de influencias biológicas, psicológicas y sociales. Esto significa que factores genéticos pueden interactuar con situaciones estresantes o experiencias traumáticas para crear problemas de ansiedad que son importantes desde el punto de vista clínico."],

            "sintomas": ["1. Síntomas cognitivos: Incluyen miedo a perder el control, a sufrir lesiones o a volverse loco, pensamientos aterradores, percepción de irrealidad, dificultad de concentración y dificultad para hablar.\n 2. Síntomas fisiológicos: Estos abarcan aumento del ritmo cardíaco, dificultad para respirar, dolor en el pecho, mareos, sudoración, náuseas, temblores, entumecimiento, debilidad y boca seca.\n 3. Síntomas de comportamiento: Comprenden la evitación de amenazas, el escape, la búsqueda de seguridad, la inquietud y la dificultad para hablar.\n 4. Síntomas afectivos: Involucran sentirse nervioso, asustado y frustrado.",
                         "1. Pensamientos asustados: Preocupación extrema por cosas malas que podrían pasar, miedo de volverse loco o preocupación exagerada por lo que piensen los demás.\n 2. Sensaciones físicas incómodas: Sentir el corazón latiendo rápido, dificultad para respirar, dolor en el pecho, mareos, sudoración excesiva, temblores y sensación de hormigueo en el cuerpo.\n 3. Comportamientos de evitación: Tratar de evitar situaciones o cosas que te asusten, como lugares abarrotados o hablar en público.\n 4. Sentimientos: Sentirse muy nervioso, tenso o asustado."],

            "tipos": ["hay varios tipos de trastornos de ansiedad:\n\n 1. Trastorno de ansiedad por separación: Esto sucede cuando alguien tiene un miedo extremo y preocupación por separarse de personas a las que está muy apegado, como sus padres. Pueden experimentar pesadillas y problemas físicos debido a este miedo.\n 2. Mutismo selectivo: En este trastorno, una persona no puede hablar en ciertas situaciones sociales, incluso si es capaz de hablar en otras circunstancias y entiende el idioma.\n 3. Fobia específica: Las personas con fobias específicas tienen un miedo intenso a cosas o situaciones particulares, como animales, inyecciones de sangre, lesiones o ciertos lugares. Este miedo es a menudo desproporcionado al peligro real.\n 4. Trastorno de ansiedad social: Aquí, alguien siente un miedo intenso en situaciones sociales, donde teme ser evaluado negativamente o avergonzado por otros.\n 5. Trastorno de pánico: Las personas con este trastorno experimentan ataques de pánico repentinos e intensos, acompañados de síntomas físicos y temor a tener otro ataque. A menudo evitan situaciones que temen que puedan desencadenar un ataque de pánico.\n 6. Agorafobia: En este trastorno, las personas temen situaciones en las que pueden sentirse atrapadas o sin ayuda, como usar el transporte público o estar en espacios abiertos.\n 7. Trastorno de ansiedad generalizada: Se caracteriza por una preocupación excesiva y persistente sobre muchas áreas de la vida, acompañada de síntomas como nerviosismo, fatiga y problemas para concentrarse.\n 8. Trastorno de ansiedad inducido por sustancias/medicamentos: Los síntomas de ansiedad pueden surgir debido al uso de sustancias o medicamentos, o durante la abstinencia.\n 9. Trastorno de ansiedad debido a otras afecciones médicas: La ansiedad puede ser causada por problemas médicos, como trastornos endocrinos, cardiovasculares, respiratorios, metabólicos o neurológicos.\n\n Estos son diferentes tipos de trastornos de ansiedad, cada uno con sus características específicas.",
                      "Existen diferentes tipos de trastornos de ansiedad que pueden afectar a las personas. Estos trastornos causan preocupación y miedo excesivos en situaciones específicas. Aquí te explico algunos de ellos de manera más sencilla:\n\n Trastorno de ansiedad por separación: Algunas personas tienen un miedo muy grande a separarse de las personas a las que están muy unidas, como sus padres. Esto puede causarles preocupación y nerviosismo.\n Mutismo selectivo: En algunos casos, las personas no pueden hablar en situaciones sociales, como en la escuela o en grupos de personas, aunque puedan hablar en otras ocasiones.\n Fobia específica: Hay personas que tienen miedo a cosas o situaciones específicas, como animales, inyecciones o ciertos lugares, y evitan estas cosas a toda costa.\n Trastorno de ansiedad social: Algunas personas sienten mucho miedo en situaciones sociales, como hablar en público o conocer a nuevas personas, porque temen que los demás los juzguen o critiquen.\n Trastorno de pánico: Esto implica tener ataques de miedo repentinos que vienen con síntomas físicos intensos, como el corazón acelerado o dificultad para respirar.\n Agorafobia: Algunas personas tienen miedo a estar en lugares públicos o abiertos, como el transporte público o grandes multitudes, porque les preocupa que no puedan escapar si se sienten mal.\n Trastorno de ansiedad generalizada: Aquí, las personas se preocupan mucho y todo el tiempo sobre muchas cosas diferentes, lo que les dificulta concentrarse y les causa nerviosismo.\n Trastorno de ansiedad debido a sustancias o medicamentos: A veces, la ansiedad es causada por el uso de drogas o medicamentos.\n Trastorno de ansiedad debido a otras afecciones médicas: En ocasiones, la ansiedad es el resultado de problemas de salud física, como problemas de tiroides o enfermedades del corazón.\n Espero que esto te ayude a entender mejor qué son los trastornos de ansiedad."],

            "diagnosticos": ['Para la evaluación de la ansiedad, se usan algunas test como el "Test Anxiety Scale" de Sarason, el "Test Anxiety Inventory" de Spielberger, "Reactions To Test" de Sarason, el "German Test Anxiety Inventory" de Hoddap, el "Inventario de Situaciones y Respuestas de Ansiedad" de Miguel Tobal y Cano Vindel, el "Cuestionario de Ansiedad en los Exámenes" de Valero, la "Cognitive Test Anxiety Scale" de Cassady y Jonson, y el "Cuestionario de Ansiedad y Rendimiento" de Ferrando Varea y Lorenzo.\n\n Cada uno de estos cuestionarios se enfoca en diferentes aspectos de la ansiedad ante los exámenes, como las preocupaciones, emociones, respuestas conductuales y situaciones que generan ansiedad. Se utilizaron para comprender mejor cómo afecta la ansiedad a los estudiantes en situaciones de evaluación.',
                             'Para evaluar la ansiedad en situaciones de evaluación, se emplean diversos cuestionarios, como el "Test Anxiety Scale" desarrollado por Sarason, el "Test Anxiety Inventory" de Spielberger, y otros como el "Cuestionario de Ansiedad en los Exámenes" de Valero, el "Inventario de Situaciones y Respuestas de Ansiedad" de Miguel Tobal y Cano Vindel, el "German Test Anxiety Inventory" de Hoddap, la "Cognitive Test Anxiety Scale" de Cassady y Jonson, así como el "Cuestionario de Ansiedad y Rendimiento" de Ferrando Varea y Lorenzo.\n\n Cada uno de estos cuestionarios se centra en diferentes aspectos de la ansiedad relacionados con las evaluaciones, como las preocupaciones, las emociones experimentadas, las respuestas conductuales y las situaciones que generan ansiedad. Estas herramientas se utilizan para obtener una comprensión más completa de cómo la ansiedad afecta a los estudiantes en situaciones de examen.',
                             'En la evaluación de la ansiedad en contextos de exámenes, se utilizan varios cuestionarios, como el "Test Anxiety Scale" de Sarason, el "Test Anxiety Inventory" de Spielberger, entre otros. Cada uno se enfoca en diferentes aspectos de la ansiedad, como las preocupaciones y emociones relacionadas con los exámenes.\n\n Estos cuestionarios ayudan a entender cómo la ansiedad afecta a los estudiantes en situaciones de evaluación.',
                             'Para evaluar la ansiedad en situaciones de exámenes, se emplean diversos cuestionarios como el "Test Anxiety Scale" de Sarason, el "Test Anxiety Inventory" de Spielberger, entre otros. Estos cuestionarios se centran en diferentes aspectos de la ansiedad relacionados con los exámenes y ayudan a comprender su impacto en los estudiantes.',
                             'En la evaluación de la ansiedad durante los exámenes, se utilizan diferentes cuestionarios, como el "Test Anxiety Scale" de Sarason o el "Test Anxiety Inventory" de Spielberger. Cada uno se enfoca en aspectos específicos de la ansiedad relacionada con las pruebas, permitiendo así comprender mejor cómo afecta a los estudiantes en estas situaciones.'],

            "tratamientos": ["Los ejercicios de relajación y la exposición gradual al entorno escolar son dos enfoques terapéuticos para reducir la ansiedad en situaciones educativas. Los ejercicios de relajación ayudan a controlar las respuestas físicas, como la frecuencia cardíaca, mientras que la exposición gradual implica enfrentar gradualmente situaciones escolares estresantes para desensibilizar la ansiedad. Ambos métodos son útiles para mejorar la confianza en entornos educativos.",
                             "Una alternativa de tratamiento es el enfoque terapéutico basado en juegos, que utiliza actividades lúdicas y juegos como herramientas para abordar los problemas emocionales, conductuales. Este enfoque se basa en la idea de que se pueden expresar sus pensamientos y emociones de manera más efectiva a través del juego, permitiéndoles abordar sus dificultades en un ambiente terapéutico seguro y atractivo.",
                             "Tratamiento para la ansiedad relacionada con el rechazo escolar que implica la evitación de situaciones sociales aversivas incluye técnicas terapéuticas como la reestructuración cognitiva y el modelado. Estas estrategias se utilizan para ayudar a los niños o adolescentes a manejar su ansiedad y superar el rechazo escolar, abordando sus pensamientos y comportamientos en situaciones sociales desafiantes.",
                             "El tratamiento efectivo para la ansiedad incluye el entrenamiento en habilidades sociales, que implica el modelado de comportamientos adecuados, el role-playing para practicar interacciones sociales, y la reestructuración cognitiva para cambiar pensamientos negativos. Además, se utiliza la exposición gradual para enfrentar situaciones sociales temidas y mejorar las habilidades en interacciones sociales."],

            "prevención": ["Aca te menciono algunas estrategias para prevenir la ansiedad:\n\n Educación sobre la ansiedad: Proporcionar a los niños y adolescentes información sobre la ansiedad, sus causas y sus efectos, para que comprendan mejor sus propios sentimientos y reacciones.\n Entrenamiento en técnicas de control de la activación: Enseñar a los jóvenes técnicas de relajación y manejo del estrés para ayudarles a gestionar sus niveles de ansiedad.\n Detección y sustitución de pensamientos automáticos negativos: Ayudar a los participantes a identificar y cambiar patrones de pensamiento negativos que contribuyen a la ansiedad.\n Autorreforzamiento abierto y encubierto: Promover la autoevaluación y el refuerzo de conductas positivas y saludables que reduzcan la ansiedad.\n Entrenamiento en solución de problemas: Enseñar habilidades para abordar situaciones estresantes y resolver problemas de manera efectiva.\n Exposición gradual: Ayudar a los participantes a enfrentar gradualmente las situaciones o estímulos que les generan ansiedad, de manera controlada y segura.",
                           "Puedo ofrecerte algunas técnicas que pueden ayudarte a prevenir y manejar la ansiedad como:\n\n Técnicas cognitivo-conductuales: Estas técnicas se centran en modificar pensamientos disfuncionales y comportamientos asociados con la ansiedad. Algunas estrategias mencionadas incluyen el entrenamiento de relajación progresiva, control de la respiración, exposición gradual a situaciones que causan ansiedad y técnicas de autocontrol.\n Técnicas psicodinámicas: Estas técnicas buscan comprender y abordar la ansiedad a través de un enfoque empático y de exploración de las emociones y las ansiedades del individuo. Un ejemplo es la terapia interpersonal.\n Otras técnicas: Se mencionan enfoques como el Counselling (consejo asistido), que implica analizar los problemas, comprenderlos y establecer objetivos y metas, así como la terapia familiar breve, que se enfoca en el cambio en el ámbito familiar para resolver problemas."]
        }